# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latestb
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run the Datagaps  BI Validation Pipeline
        run: |
          echo Running Datagaps BI Validation Pipeline
          curl -X POST "$BIVALIDATOR_TESTPLAN_URL" -H "Content-Type: application/json" --data "{\"testPlanId\": \"$TESTPLAN_ID\", \"userName\": \"$USERNAME\", \"password\": \"$PASSWORD\"}"
